NAME: 'ex1'

MODE: '2d'

TRAIN:
  Epoch: 200
  Alpha: 0.6
  OPTIMIZER:
    TYPE: 'adam'
    Lr: 0.001
    WEIGHT_DECAY: 0
  Out_dim: 1
  Ray_hidden_dim: 100
  N_task: 2
  Ref_point: "2,2"
  Solver:
    Cheby:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    LS:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    Utility:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    KL:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    Cosine:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    Cauchy:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    Log:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    Prod:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    AC:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    MC:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'
    HV:
      Num_hidden_layer: 1
      Last_activation: 'sigmoid'

TEST:
  Num_ray_init: 1000
  Num_ray_test: 30